### ISSUE TITLE
Link on README not correct

### ISSUE THREAD

**Issue by mirenbz** [fathominfo/noceilings-data#5]
On the first paragraph of the README.md page, where it says 

> To download all of the data in a single file, http://noceilings.org/download.

The URL is not correctly linked. It should be pointing to http://noceilings.org/download but it's linked to https://github.com/fathominfo/noceilings-data/blob/master/click%20here (¿?) instead.

**Comment by benfry** [comment]
Sorry about that, the linked text and the link url were backwards in the file. Now fixed!
