### ISSUE TITLE
Update data

### ISSUE THREAD

**Issue by arcuellar88** [fathominfo/noceilings-data#8]
Hello!

do you have plans to update the data? If you have, are you going to keep the same structure in Github? 

Thank you in advanced. 

Alejandro R.

**Comment by benfry** [comment]
We hope to, but we don't have an update on the calendar yet. If we do, we'll try to keep the same structure as much as possible. And please let us know if you make something with it!

**Comment by arcuellar88** [comment]
Thank you! I will
