### ISSUE TITLE
'Unkown' countries/ISO codes in data files...

### ISSUE THREAD

**Issue by Micha789** [fathominfo/noceilings-data#9]
Hi, just started looking at this data for a project on data visualisation...

I'm finding ISO (country) codes in the data files for countries that aren't actually listed in countries.csv.
This is worrying as I'm wondering whether it's incorrect data now...

Some of the ISO codes in the data files seem to be a code for a region instead of a country (e.g. SSE - Sub Saharan Africa). 
But there are only only 7 codes for regions listed in the regions file, and in some data files I'm coming up with over 30 ISOs that aren't in the official countries.csv file.

Anyone has any thoughts/suggestions?

Thanks!
Micha

**Comment by benfry** [comment]
What ISO codes are missing from the countries file? You can find a complete list here: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3

The region codes are different from ISO country codes; you can see the list of them in the region files, i.e.: https://github.com/fathominfo/noceilings-data/blob/master/region-names.json and the mapping of regions to country codes is here: https://github.com/fathominfo/noceilings-data/blob/master/region-countries.json

**Comment by Micha789** [comment]
Hi Ben and thanks for getting back to me.

I had a look at education theme indicator files and stopped because I was coming up with loads of 'unknown' countries in many of the files. Example of such country codes are: AAE, ACE, ANE, and many others - they don't appear in the list you linked to above, or in countries.csv
Some of the country codes were actually region codes, but there are a lot more 'unknown' codes than region codes.

Example files with such countries include NERAPRFE.csv, NERAPRGP.csv, NERAPRMA.csv, and several more.

I'm attaching a log file I created that lists these files within the education theme, and the 'unknown' countries. 

I've check both files and my code several times, but just in case I've done something very silly and am wasting your time, my sincere apologies!

I wonder whether the cause is data entry error...?
Also, these 'unknown' countries seem to be in the last rows of files...

I'd really like to explore this dataset for a data vis project, but don't want to invest more effort than I've already done without knowing exactly what's what.
Thanks and best,
Micha.
[20200717-test-education.log](https://github.com/fathominfo/noceilings-data/files/5080869/20200717-test-education.log)

**Comment by benfry** [comment]
I believe that they're made-up codes for other subcategories, the same way that the “regions” have 3-digit codes but aren't actually countries. (It's long enough ago that I don't have an exact recollection…) 

The data was provided by [EIU](https://www.eiu.com/), who had a few such designations but they weren't consistent enough to be used in the visualizations. 

Suffice to say, if you're looking for country data, just stick with the countries—no need to worry about the extraneous designations like this.

**Comment by Micha789** [comment]
Thanks for checking, Ben. Much appreciated.
It makes some sense that they are additional codes and not errors, as they the same unknown country codes keep coming up in different files...I guess if they were data entry errors they might not be so consistent 👍 
Cheers,
Micha.
